env:
  - GO111MODULE=auto
before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - '386'
      - amd64
    ldflags:
      - -s -w

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^Merge pull request'
      - '^Merge branch'

archives:
  -
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
