env:
  - GO111MODULE=auto

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge pull request"
      - "^Merge branch"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

brews:
  - tap:
      owner: thazelart
      name: homebrew-tap
    goarm: "7"
    homepage: https://github.com/thazelart/golang-cli-template
    description: A Golang cli template.
    license: Apache 2.0
    test: |
      system "#{bin}/golang-cli-template version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "golang-cli-template"
      bash_completion.install "completions/golang-cli-template.bash" => "golang-cli-template"
      zsh_completion.install "completions/golang-cli-template.zsh" => "_golang-cli-template"
      fish_completion.install "completions/golang-cli-template.fish"
      man1.install "manpages/golang-cli-template.1.gz"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/thazelart/golang-cli-template
    description: A Golang cli template.
    maintainer: Thibault HAZELART <thazelart@gmail.com>
    license: Apache 2.0
    vendor: thazelart
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/golang-cli-template.bash
        dst: /usr/share/bash-completion/completions/golang-cli-template
        file_info:
          mode: 0644
      - src: ./completions/golang-cli-template.fish
        dst: /usr/share/fish/vendor_completions.d/golang-cli-template.fish
        file_info:
          mode: 0644
      - src: ./completions/golang-cli-template.zsh
        dst: /usr/share/zsh/vendor-completions/_golang-cli-template
        file_info:
          mode: 0644
      - src: ./manpages/golang-cli-template.1.gz
        dst: /usr/share/man/man1/golang-cli-template.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/golang-cli-template/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

release:
  footer: |
    **Full Changelog**: https://github.com/thazelart/golang-cli-template/compare/{{ .PreviousTag }}...{{ .Tag }}
