name: Security Report
description: Report a security issue
labels: [security, triage]
assignees:
  - thazelart
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security report.
        Please check the existing issues before raising.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and specific description of what the issue is
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Do you have a proposed solution for this issue?
      description: Describe what solutions you've considered
    validations:
      required: false
  - type: textarea
    id: system-info
    attributes:
      label: System info
      placeholder: |
        OS: [e.g. Ubuntu]
        OS version: [e.g. 20.04]
        golang-cli-template version: [e.g. 1.0.0]
    validations:
      required: false
