name: Documentation Request
description: Request a change or addition in the documentation
labels: [documentation, triage]
assignees:
  - thazelart
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation request! Please fill the form below.
  - type: textarea
    id: info
    attributes:
      label: Describe your need.
      description: A clear and concise description of the missing / incomplete or wrong documentation section.
      placeholder: I can't find any revelent documentation for [...]
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I did search for other open and closed issues before opening this.
          required: true
